# Use zsh as default
set -g default-shell /bin/zsh

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "tmux-256color" # Use tmux's terminfo entry for modern terminal support
set -ag terminal-overrides ",*:RGB" # Enable true-color for compatible terminals

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed

# General
set -g mouse on                 # Enable mouse support
set -g set-clipboard on         # Use system clipboard
set -g detach-on-destroy off    # Don't exit from tmux when closing a session
set -g escape-time 0            # Remove delay for exiting insert mode with ESC in Neovim
set -g focus-events on          # Forward terminal focus gained/lost events to apps in tmux
set -g history-limit 1000000    # Increase history size (from 2,000)
set -g allow-passthrough on     # Allow programs in the pane to bypass tmux (e.g. for image preview)
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'

# Refresh config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message 'tmux config reloaded'

# Preserve the active pane directory for new windows and splits
unbind c
bind c new-window -c '#{pane_current_path}'
unbind '"'
bind '"' split-window -v -c '#{pane_current_path}'
unbind %
bind % split-window -h -c '#{pane_current_path}'
unbind !
bind ! break-pane

# tpm plugin manager
set -g @plugin 'tmux-plugins/tpm'

# List of plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'    # Persist tmux sessions after pc restart
set -g @plugin 'tmux-plugins/tmux-continuum'    # Auto saves sessions every 15 min


# Style
fg="#abb2bf"
bg="#23272e"
blue="#4aa5f0"
comment="#4f5666"
black="#3f4451"

# Status bar
set -g status on                # Force a single status row when the config is reloaded
set -g status-interval 3        # Update the status bar every 3 seconds (default: 15 seconds)
set -g status-position top
set -g status-left-length 30
set -g status-style "bg=default,fg=${fg}"
set -g status-left "#[fg=${bg},bg=${blue},bold] #S #[bg=default] "
set -g status-right "#[fg=${blue}]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,} "
set -g status-right-length 50

set -g window-status-current-format "#[fg=${blue},bold] #I:#W "
set -g window-status-format "#[fg=${comment}] #I:#W "
set -g message-style "bg=default,fg=${blue}"
set -g message-command-style "bg=default,fg=${blue}"
set -g mode-style "fg=${bg},bg=${blue}"
set -g pane-border-style "fg=${comment}"
set -g pane-active-border-style "fg=${blue}"
setw -g clock-mode-colour ${blue}

# Resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @resurrect-processes '"~opencode->opencode *"'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
