[tools]
atuin = { version = "latest", os = ["linux", "macos"] }
btop = { version = "latest", os = ["linux"] }
bun = "latest"
bat = "latest"
cmake = "latest"
croc = "latest"
doppler = "latest"
"github:eza-community/eza" = { version = "latest", os = ["linux", "windows"] }
"cargo:eza" = { version = "latest", os = ["macos"] }
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
gopass = "latest"
grex = { version = "latest", os = ["linux", "windows"] }
"cargo:grex" = { version = "latest", os = ["macos"] }
java = "temurin-21"
jq = "latest"
lazygit = "latest"
node = "lts"
pnpm = "latest"
python = "latest"
ripgrep = "latest"
rust = "stable"
starship = "latest"
opencode = { version = "latest", os = ["linux", "macos"] }
"github:Kilo-Org/kilocode" = "latest"
yazi = "latest"
zig = "latest"
zoxide = "latest"
terraform = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
terraform-docs = "latest"
codex = "latest"
gemini-cli = "latest"
lazydocker = "latest"
yq = "latest"
